-- require('kareem.plugins.alpha')
-- require('kareem.plugins.auto-session')
require('kareem.plugins.autocommands')
-- require('kareem.plugins.autopairs')
require('kareem.plugins.bufferline')
require('kareem.plugins.comment')
require('kareem.plugins.completion')
require('kareem.plugins.conform')
-- require('kareem.plugins.gitsigns')
require('kareem.plugins.indent-blankline')
require('kareem.plugins.language')
-- require('kareem.plugins.linting')
require('kareem.plugins.lualine')
require('kareem.plugins.nvim-tree')
require('kareem.plugins.nvim-treesitter')
require('kareem.plugins.substitute')
require('kareem.plugins.surround')
require('kareem.plugins.telescope')
require('kareem.plugins.todo-comments')
require('kareem.plugins.trouble')
require('kareem.plugins.keymaps')

require('dressing').setup()
vim.keymap.set('n', '<leader>sm', '<cmd>MaximizerToggle<CR>', { desc = 'Maximize/minimize a split' })
vim.keymap.set('n', '<leader>lg', '<cmd>LazyGit<cr>', { desc = 'Open lazy git' })
